name: Bump Helm Chart Version
description: Bump a Helm Chart Version Locally
branding:
  icon: hard-drive
  color: blue
inputs:
  app_version:
    description: to also bump app-version
    default: "true"
    required: false
  level:
    description: patch/minor/major
    required: true
  chart-path:
    description: the directory path to the specified chart (without / at the end)
    required: true
  add_hash:
    description: to also add git commit hash as metadata
    default: "false"
    required: false
outputs:
  chart:
    description: "Chart name"    
    value: ${{ steps.chart-name.outputs.chart }}
runs:
  using: "composite"
  steps:
    - name: Install PyBump
      run: |
        python3 -m pip install pybump
      shell: bash

    - name: Automated Version Bump
      id: version-bump
      run: |
        if [[ ${{ fromJSON(inputs.app_version) }} ]]
        then
          if [[ ${{ fromJSON(inputs.add_hash) }} ]]
          then
            pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --auto
          else
            pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }} --app-version
          fi
        else
          if [[ ${{ fromJSON(inputs.add_hash) }} ]]
          then
            pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --auto
          else
            pybump bump --file ${{ inputs.chart-path }}/Chart.yaml --level ${{ inputs.level }}
          fi
        fi      
      shell: bash        

    - name: Output Name
      id: chart-name
      run: |
        echo "::set-output name=chart::$(basename ${{ inputs.chart-path }})"
      shell: bash
